PROJECT_MVC/Controllers/BookViewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PROJECT_MVC.Models;

namespace PROJECT_MVC.Controllers
{
    public class BookViewController : Controller
    {
        ProjectDBEntities dbobj = new ProjectDBEntities();
        // GET: BookView
        public ActionResult BookView_Load(BookDB objcls)
        {
            return View(dbobj.BookTabs.ToList());
        }
    }
}

PROJECT_MVC/Controllers/HomePageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PROJECT_MVC.Controllers
{
    public class HomePageController : Controller
    {
        // GET: HomePage
        public ActionResult HIndex()
        {
            return View();
        }
    }
}

PROJECT_MVC/Controllers/InsertController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PROJECT_MVC.Models;
using System.IO;

namespace PROJECT_MVC.Controllers
{
    public class InsertController : Controller
    {
        // GET: Insert
        ProjectDBEntities dbobj = new ProjectDBEntities();
        public ActionResult Register_Load()
        {
            return View();
        }
        public ActionResult Register_Click(InsertDB objcls,HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file.ContentLength > 0)
                {
                    string fname = Path.GetFileName(file.FileName);
                    var s = Server.MapPath("~/PHS");
                    string pa = Path.Combine(s, fname);
                    file.SaveAs(pa);
                    var fullpath = Path.Combine("~\\PHS", fname);
                    objcls.Photo = fullpath;
                }
                dbobj.sp_insert(objcls.Name, objcls.Age, objcls.Address, objcls.Email, objcls.Photo, objcls.Username, objcls.Password);
                objcls.msg = "Inserted Succesfully!";
                return View("Register_Load", objcls);
            }
            return View("Register_Load", objcls);
        }
    }
}

PROJECT_MVC/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Core.Objects;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PROJECT_MVC.Models;

namespace PROJECT_MVC.Controllers
{
    public class LoginController : Controller
    {
        ProjectDBEntities dbobj = new ProjectDBEntities();
        // GET: Login
        public ActionResult Login_Load()
        {
            return View();
        }
        public ActionResult Home()
        {
            return View();
        }
        public ActionResult Login_Click(LoginDB objcls)
        {
            if (ModelState.IsValid)
            {
                ObjectParameter op = new ObjectParameter("status", typeof(int));
                dbobj.sp_login(objcls.Username, objcls.Password, op);
                int val = Convert.ToInt32(op.Value);
                if(val == 1)
                {
                    Session["UName"] = objcls.Username;
                    return RedirectToAction("Home");
                }
                else
                {
                    ModelState.Clear();
                    objcls.msg = "Invalid Username/Password";
                    return View("Login_Load",objcls);
                }
            }
            return View("Login_Load", objcls);
        }
    }
}

PROJECT_MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Book Worms", "HIndex", "HomePage", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Login_Load", "Login")</li>
                    <li>@Html.ActionLink("All Book Details", "BookView_Load", "BookView")</li>
                    <li>@Html.ActionLink("Register", "Register_Load", "Insert")</li>
                    <li>@Html.ActionLink("All Users", "Display_Load", "DisplayAll")</li>
                    <li>@Html.ActionLink("About Us", "Index", "Home")</li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>