PROJECT_MVC/Controllers/BookViewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PROJECT_MVC.Models;

namespace PROJECT_MVC.Controllers
{
    public class BookViewController : Controller
    {
        ProjectDBEntities dbobj = new ProjectDBEntities();
        // GET: BookView
        public ActionResult BookView_Load(BookDB objcls)
        {
            return View(dbobj.BookTabs.ToList());
        }
    }
}

PROJECT_MVC/Controllers/ChangePasswordController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Core.Objects;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PROJECT_MVC.Models;

namespace PROJECT_MVC.Controllers
{
    public class ChangePasswordController : Controller
    {
        ProjectDBEntities dbobj = new ProjectDBEntities();
        // GET: ChangePassword
        public ActionResult Password_Load()
        {
            return View();
        }
        public ActionResult Password_Click(ChangePwd obj)
        {
            if (ModelState.IsValid)
            {
                ObjectParameter op = new ObjectParameter("status", typeof(int));
                dbobj.sp_pwdchange(Session["UName"].ToString(), obj.OldPassword, obj.NewPassword, op);
                int val = Convert.ToInt32(op.Value);
                if (val != 0)
                {
                    obj.msg = "Changed Password Successfully!";
                    return View("Password_Load", obj);
                }
                else
                {
                    obj.msg = "Password Mismatch!";
                    return View("Password_Load", obj);
                }
            }
            return View("Password_Load", obj);
        }
    }
}

PROJECT_MVC/Controllers/DisplayAllController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PROJECT_MVC.Controllers
{
    public class DisplayAllController : Controller
    {
        ProjectDBEntities dbobj = new ProjectDBEntities();
        // GET: DisplayAll
        public ActionResult Display_Load()
        {
            return View(dbobj.MVC_Tab.ToList());
        }
    }
}

PROJECT_MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PROJECT_MVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

PROJECT_MVC/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Core.Objects;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PROJECT_MVC.Models;

namespace PROJECT_MVC.Controllers
{
    public class LoginController : Controller
    {
        ProjectDBEntities dbobj = new ProjectDBEntities();
        // GET: Login
        public ActionResult Login_Load()
        {
            return View();
        }
        public ActionResult Home()
        {
            return View();
        }
        public ActionResult Login_Click(LoginDB objcls)
        {
            if (ModelState.IsValid)
            {
                ObjectParameter op = new ObjectParameter("status", typeof(int));
                dbobj.sp_login(objcls.Username, objcls.Password, op);
                int val = Convert.ToInt32(op.Value);
                if(val == 1)
                {
                    Session["UName"] = objcls.Username;
                    return RedirectToAction("Home");
                }
                else
                {
                    ModelState.Clear();
                    objcls.msg = "Invalid Username/Password";
                    return View("Login_Load",objcls);
                }
            }
            return View("Login_Load", objcls);
        }
    }
}

PROJECT_MVC/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PROJECT_MVC.Models;

namespace PROJECT_MVC.Controllers
{
    public class ProfileController : Controller
    {
        ProjectDBEntities dbobj = new ProjectDBEntities();
        // GET: Profile
        public ActionResult Profile_Load(ProfileViewAndEdit objcls)
        {
            var getdata = dbobj.sp_pview(Session["UName"].ToString()).FirstOrDefault();
            return View( new ProfileViewAndEdit
            {
                Name = getdata.Name,
                Age = getdata.Age,
                Address = getdata.Address,
                Email = getdata.Email,
                Photo = getdata.Photo
            }
                );
        }
        public ActionResult Profile_Update(ProfileViewAndEdit objcls)
        {
            dbobj.sp_update(Session["UName"].ToString(), objcls.Age, objcls.Address);

            var getdata = dbobj.sp_pview(Session["UName"].ToString()).FirstOrDefault();
            return View("Profile_Load", new ProfileViewAndEdit
            {
                Name = getdata.Name,
                Age = getdata.Age,
                Address = getdata.Address,
                Email = getdata.Email,
                Photo = getdata.Photo
            });

            //objcls.msg = "Updated Successfully!";
        }
    }
}

PROJECT_MVC/Views/Login/Home.cshtml
@{
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<center>
    <div><img src="~/PHS/bannermvc.jpg" width="1100px" /></div>
    <h2>Home Page</h2>
    <div>
        @Html.ActionLink("Summary of Books", "BookView_Load", "BookView")
    </div>
    <div>
        @Html.ActionLink("View User Profile", "Profile_Load", "Profile")
    </div>
    <div>
        @Html.ActionLink("Change Password", "Password_Load", "ChangePassword")
    </div>
    <div>
        @Html.ActionLink("All the details of clients", "Display_Load", "DisplayAll")
    </div>
</center>

PROJECT_MVC/Views/Login/Login_Load.cshtml
@model PROJECT_MVC.Models.LoginDB
@{
    ViewBag.Title = "Login_Load";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<center>
    <div>
        @using (Html.BeginForm("Login_Click", "Login", FormMethod.Post))
        {
            <div><img src="~/PHS/bannermvc.jpg" width="1100px" /></div>

            <br />
            <h2>Login Page</h2>
            <div>
                <label>Username:</label>
            </div>
            <div>
                @Html.TextBoxFor(m => m.Username)
                @Html.ValidationMessageFor(m => m.Username)
            </div>
            <div>
                <label>Password:</label>
            </div>
            <div>
                @Html.TextBoxFor(m => m.Password)
                @Html.ValidationMessageFor(m => m.Password)
            </div>
            <div>
                <input id="Button1" type="submit" value="Login" />
                <br />
                @Html.DisplayFor(m => m.msg)
            </div>
        }
    </div>
    <br />
    <div>
        @Html.ActionLink("All the details of clients", "Display_Load", "DisplayAll")
    </div>
</center>