PROJECT_MVC/Controllers/BookInsertController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PROJECT_MVC.Models;

namespace PROJECT_MVC.Controllers
{
    public class BookInsertController : Controller
    {
        ProjectDBEntities dbobj = new ProjectDBEntities();
        // GET: BookInsert
        public ActionResult Book_Load()
        {
            return View();
        }
        public ActionResult Book_Click(BookDB objcls)
        {
            dbobj.bookinsert(objcls.BookName, objcls.BookSummary);
            objcls.msg = "Inserted Successfully!";
            Session["BName"] = objcls.BookName;
            return View("Book_Load",objcls);
        }
    }
}

PROJECT_MVC/Views/BookInsert/Book_Load.cshtml
@model PROJECT_MVC.Models.BookDB
@{
    ViewBag.Title = "Book_Load";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<center>
    <h1>Book Insertion</h1>
    <div>
        @using (Html.BeginForm("Book_Click", "BookInsert", FormMethod.Post))
        {
            <div>
                <label>Book Name:</label>
            </div>
            <div>
                @Html.TextBoxFor(m => m.BookName)
            </div>
            <div>
                <label>Book Summary:</label>
            </div>
            <div>
                @Html.TextAreaFor(m => m.BookSummary)
            </div>
            <div>
                <input id="Button1" type="submit" value="Insert" />
                @Html.DisplayFor(m => m.msg)
            </div>
        }
    </div>
</center>